import{a as c,S as d,i as l}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function u(t,r=1,n=12){const e=`https://pixabay.com/api/?${new URLSearchParams({key:"44785846-fbfadd775113e3685d7630ccf",q:t,image_type:"photo",orientation:"horizontal",safesearch:!1,per_page:n,page:r})}`;return await c.get(e).then(o=>(console.log(o),{images:o.data.hits,totalImages:o.data.totalHits})).catch(o=>console.log(o))}function g(){const t=document.getElementById("gallery");t.innerHTML=""}let i;function f(t){document.getElementById("gallery").insertAdjacentHTML("beforeend",t.map(n=>`
        <div class="gallery-item">
            <a href="${n.largeImageURL}">
                <img src="${n.webformatURL}" alt="${n.tags}" />
            </a>
            <div class="info">
                <p><strong>Likes:</strong><br>${n.likes}</p>
                <p><strong>Views:</strong><br>${n.views}</p>
                <p><strong>Comments:</strong><br>${n.comments}</p>
                <p><strong>Downloads:</strong><br>${n.downloads}</p>
            </div>
        </div>`).join("")),i?i.refresh():i=new d(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function m(){const t=document.getElementById("loader");t.style.display="inline-block"}function p(){const t=document.getElementById("loader");t.style.display="none"}function y(){l.warning({title:"Not found",message:"Sorry, there are no images matching search query. Please try again!",position:"topRight"})}function h(){l.info({title:"End of List",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function L(t){l.error({title:"Error",message:t.message,position:"topRight"})}function b(){const t=document.getElementById("loadMoreButton");t.style.display="inline-block"}function B(){const t=document.getElementById("loadMoreButton");t.style.display="none"}document.getElementById("searchButton").addEventListener("click",async()=>{const t=document.getElementById("searchInput").value.trim();if(t==="")return;m(),g();const r=15,n=1;try{const{images:s,totalImages:e}=await u(t,n,r);console.log(s),console.log(e),s.length===0?y():(f(s),b()),n*r>=e&&(B(),h())}catch(s){L(s)}finally{p()}});
//# sourceMappingURL=commonHelpers.js.map
