import{a as B,S as I,i as u}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();async function g(e,r=1,n=12){const t=`https://pixabay.com/api/?${new URLSearchParams({key:"44785846-fbfadd775113e3685d7630ccf",q:e,image_type:"photo",orientation:"horizontal",safesearch:!1,per_page:n,page:r})}`;return await B.get(t).then(o=>(console.log(o),{images:o.data.hits,totalImages:o.data.totalHits})).catch(o=>console.log(o))}function b(){const e=document.getElementById("gallery");e.innerHTML=""}let d;function f(e){document.getElementById("gallery").insertAdjacentHTML("beforeend",e.map(n=>`
        <div class="gallery-item">
            <a href="${n.largeImageURL}">
                <img src="${n.webformatURL}" alt="${n.tags}" />
            </a>
            <div class="info">
                <p><strong>Likes:</strong><br>${n.likes}</p>
                <p><strong>Views:</strong><br>${n.views}</p>
                <p><strong>Comments:</strong><br>${n.comments}</p>
                <p><strong>Downloads:</strong><br>${n.downloads}</p>
            </div>
        </div>`).join("")),d?d.refresh():d=new I(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function m(){const e=document.getElementById("loader");e.style.display="inline-block"}function y(){const e=document.getElementById("loader");e.style.display="none"}function w(){u.warning({title:"Not found",message:"Sorry, there are no images matching search query. Please try again!",position:"topRight"})}function p(){u.info({title:"End of List",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function h(e){u.error({title:"Error",message:e.message,position:"topRight"})}function E(){const e=document.getElementById("loadMoreButton");e.style.display="inline-block"}function L(){const e=document.getElementById("loadMoreButton");e.style.display="none"}let a="sert",s=1;const i=3;document.getElementById("searchButton").addEventListener("click",async()=>{if(s=1,a=document.getElementById("searchInput").value.trim(),a!==""){b();try{m();const{images:e,totalImages:r}=await g(a,s,i);e.length===0?w():(f(e),E()),s*i>=r&&(L(),p())}catch(e){h(e)}finally{y()}}});document.getElementById("loadMoreButton").addEventListener("click",async()=>{s++;try{m();const{images:e,totalImages:r}=await g(a,s,i);e.length===0?showNoResultsMessage():(f(e),s*i>=r&&(L(),p()))}catch(e){h(e)}finally{y()}});
//# sourceMappingURL=commonHelpers.js.map
